In [1]:
import torch
import torch.nn as nn

In [2]:
%config Completer.use_jedi = False

In [3]:
RANDOM_SEED = 42

In [4]:
torch.manual_seed(RANDOM_SEED)
random_var = torch.rand(1, 3, 4, 4)

In [5]:
momentum = .1
# num_features corresponds to number of channels
batch_norm2d = nn.BatchNorm2d(num_features=3, momentum=momentum)
batch_norm2d.running_mean, batch_norm2d.running_var, batch_norm2d.weight

(tensor([0., 0., 0.]),
 tensor([1., 1., 1.]),
 Parameter containing:
 tensor([1., 1., 1.], requires_grad=True))

In [6]:
norm_random_var = batch_norm2d(random_var)

In [7]:
batch_norm2d.running_mean, batch_norm2d.running_var, batch_norm2d.weight

(tensor([0.0649, 0.0419, 0.0631]),
 tensor([0.9072, 0.9085, 0.9047]),
 Parameter containing:
 tensor([1., 1., 1.], requires_grad=True))

In [8]:
channel = 1
mu = (1 - momentum) * 0.0 + momentum * torch.mean(random_var[0][channel])
var = (1 - momentum) * 1.0 + momentum * torch.var(random_var[0][channel], unbiased=True) 
mu, var

(tensor(0.0419), tensor(0.9085))

# Upsampling

In [9]:
var = torch.arange(1, 5, dtype=torch.float32).view(1, 1, 2, 2)
var

tensor([[[[1., 2.],
          [3., 4.]]]])

In [10]:
nn.Upsample(scale_factor=2, mode='nearest')(var)

tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])

In [12]:
nn.Upsample(scale_factor=2, mode='bilinear', align_corners=False)(var)  # align_corners=False

tensor([[[[1.0000, 1.2500, 1.7500, 2.0000],
          [1.5000, 1.7500, 2.2500, 2.5000],
          [2.5000, 2.7500, 3.2500, 3.5000],
          [3.0000, 3.2500, 3.7500, 4.0000]]]])

In [13]:
nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)(var)  # align_corners=False

tensor([[[[1.0000, 1.3333, 1.6667, 2.0000],
          [1.6667, 2.0000, 2.3333, 2.6667],
          [2.3333, 2.6667, 3.0000, 3.3333],
          [3.0000, 3.3333, 3.6667, 4.0000]]]])

In [38]:
data = torch.tensor([
    [[10, 20],
     [30, 40]],
    [[2, 1],
     [4, 3]], 
    [[2, 1],
     [4, 3]]],
    dtype=torch.float32).view(1, 3, 2, 2)
data

tensor([[[[10., 20.],
          [30., 40.]],

         [[ 2.,  1.],
          [ 4.,  3.]],

         [[ 2.,  1.],
          [ 4.,  3.]]]])

In [42]:
nn.Upsample(scale_factor=2, mode='bilinear', align_corners=False)(data)  # align_corners=False

tensor([[[[10.0000, 12.5000, 17.5000, 20.0000],
          [15.0000, 17.5000, 22.5000, 25.0000],
          [25.0000, 27.5000, 32.5000, 35.0000],
          [30.0000, 32.5000, 37.5000, 40.0000]],

         [[ 2.0000,  1.7500,  1.2500,  1.0000],
          [ 2.5000,  2.2500,  1.7500,  1.5000],
          [ 3.5000,  3.2500,  2.7500,  2.5000],
          [ 4.0000,  3.7500,  3.2500,  3.0000]],

         [[ 2.0000,  1.7500,  1.2500,  1.0000],
          [ 2.5000,  2.2500,  1.7500,  1.5000],
          [ 3.5000,  3.2500,  2.7500,  2.5000],
          [ 4.0000,  3.7500,  3.2500,  3.0000]]]])